---
production:
  services:
    tenants:
      uri: "http://tenants:80/api/"
      apiVersion: v1
    registry:
      uri: "http://registry:80/api/"
      apiVersion: v1
  port: 80
  logger: 'info'
development:
  services:
    tenants:
      uri: "http://localhost:5031/api/"
      apiVersion: v1
    registry:
      uri: "http://localhost:8081/api/"
      apiVersion: v1
  port: 5000
  logger: 'debug'
