---
production:
  services:
    tenants:
      uri: "http://supervisor.governify.io/api/"
      apiVersion: v1
    registry:
      uri: "http://supervisor.oai.governify.io/agreements/api/"
      apiVersion: v1
  port: 80
development:
  services:
    tenants:
      uri: "http://localhost:3001/api/"
      apiVersion: v1
    registry:
      uri: "http://localhost:5000/agreements/api/"
      apiVersion: v1
  port: 5000
