---
production:
  services:
    tenants:
      uri: "http://supervisor.governify.io/api/"
      apiVersion: v1
    registry:
      uri: "http://registry:8081/api/"
      apiVersion: v1
  port: 80
  logger: 'info'
development:
  services:
    tenants:
      uri: "http://localhost:3001/api/"
      apiVersion: v1
    registry:
      uri: "http://localhost:8081/api/"
      apiVersion: v1
  port: 5000
  logger: 'debug'
